id: 7c809a19f8fc4fe4aba81ddfbebd4841
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_676-The_Dharani_Essence_of_Immeasurable_Longevity_and_Wisdom-v1
  language: en
  author: ''
  volume: {}
